In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('hospital_patient_records_dirty.csv') 
print(df.shape) 
df.info() 
df.describe(include='all') 
df.sample(10)

(423, 13)
<class 'pandas.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      423 non-null    int64
 1   Name           423 non-null    str
 2   Age            390 non-null    float64
 3   Gender         398 non-null    str
 4   Diagnosis      385 non-null    str
 5   City           396 non-null    str
 6   BloodType      396 non-null    str
 7   HeightCM       396 non-null    float64
 8   WeightKG       393 non-null    float64
 9   SystolicBP     392 non-null    float64
 10  AdmissionDate  423 non-null    str
 11  HasInsurance   393 non-null    str
 12  BillingAmount  391 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 64.6 KB

,PatientID,Name,Age,Gender,Diagnosis,City,BloodType,HeightCM,WeightKG,SystolicBP,AdmissionDate,HasInsurance,BillingAmount
371,5139,Nimra Javed,54.0,Female,migraine,Multan,O+,158.0,110.0,131.0,08/12/2021,YES,$949.71
374,5343,Mariam Shah,-36.0,f,influenza,KARACHI,AB-,168.3,67.1,131.0,2022/02/24,0,4783.25
359,5174,Waleed Ahmed,60.0,M,NaN,Multan,A+,156.1,69.5,116.0,2022/12/25,YES,PKR 4858.83
273,5073,Salman Farooq,34.0,FEMALE,Bronchitis,NaN,O-,166.8,78.9,125.0,16/10/2023,1,3185.45
177,5033,Fahad Dar,40.0,MALE,Anemia,islamabad,B-,169.4,83.4,NaN,2024/07/25,No,1152.37
285,5183,Areeba Javed,34.0,f,Asthma,Lahore,NaN,152.2,NaN,113.0,8/21/2021,Y,1073.84
247,5188,Waleed Ahmed,74.0,M,MIGRAINE,quetta,B-,176.2,75.7,NaN,2022/09/23,Y,$2595.86
195,5006,Mehwish Gill,45.0,female,hypertension,Multan,A-,169.4,36.3,126.0,"4 Jul, 2023",NO,PKR 4986.2
244,5094,Rida Ahmed,21.0,NaN,BRONCHITIS,lahore,O-,173.7,51.4,NaN,2022-11-27,NO,2642.61
133,5260,Adnan Raza,66.0,F,Bronchitis,Lahore,O+,177.1,107.8,101.0,11/03/2021,Yes,PKR 3338.26

In [7]:
df = pd.read_csv('hospital_patient_records_dirty.csv') 
df.shape 
df.info() 
df.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      423 non-null    int64
 1   Name           423 non-null    str
 2   Age            390 non-null    float64
 3   Gender         398 non-null    str
 4   Diagnosis      385 non-null    str
 5   City           396 non-null    str
 6   BloodType      396 non-null    str
 7   HeightCM       396 non-null    float64
 8   WeightKG       393 non-null    float64
 9   SystolicBP     392 non-null    float64
 10  AdmissionDate  423 non-null    str
 11  HasInsurance   393 non-null    str
 12  BillingAmount  391 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 64.6 KB

,PatientID,Name,Age,Gender,Diagnosis,City,BloodType,HeightCM,WeightKG,SystolicBP,AdmissionDate,HasInsurance,BillingAmount
count,423.000000,423,390.000000,398,385,396,396,396.000000,393.000000,392.000000,423,393,391
unique,NaN,308,NaN,11,32,43,8,NaN,NaN,NaN,391,11,370
top,NaN,Salman Javed,NaN,MALE,arthritis,rawalpindi,B-,NaN,NaN,NaN,12/09/2024,Y,PKR 2646.75
freq,NaN,4,NaN,45,22,15,57,NaN,NaN,NaN,4,55,3
mean,5200.770686,NaN,45.310256,NaN,NaN,NaN,NaN,163.745707,78.224173,126.025510,NaN,NaN,NaN
std,116.052415,NaN,30.313082,NaN,NaN,NaN,NaN,19.314527,51.307581,22.013699,NaN,NaN,NaN
min,5001.000000,NaN,-74.000000,NaN,NaN,NaN,NaN,10.500000,33.400000,75.000000,NaN,NaN,NaN
25%,5102.500000,NaN,31.000000,NaN,NaN,NaN,NaN,158.775000,62.100000,114.750000,NaN,NaN,NaN
50%,5201.000000,NaN,44.000000,NaN,NaN,NaN,NaN,166.150000,71.000000,125.000000,NaN,NaN,NaN
75%,5299.500000,NaN,57.000000,NaN,NaN,NaN,NaN,172.525000,81.100000,134.000000,NaN,NaN,NaN
max,5400.000000,NaN,195.000000,NaN,NaN,NaN,NaN,190.900000,489.300000,306.000000,NaN,NaN,NaN

In [8]:
print(df.info())
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      423 non-null    int64
 1   Name           423 non-null    str
 2   Age            390 non-null    float64
 3   Gender         398 non-null    str
 4   Diagnosis      385 non-null    str
 5   City           396 non-null    str
 6   BloodType      396 non-null    str
 7   HeightCM       396 non-null    float64
 8   WeightKG       393 non-null    float64
 9   SystolicBP     392 non-null    float64
 10  AdmissionDate  423 non-null    str
 11  HasInsurance   393 non-null    str
 12  BillingAmount  391 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 64.6 KB
None
PatientID         0
Name              0
Age              33
Gender           25
Diagnosis        38
City             27
BloodType        27
HeightCM         27
WeightKG         30
SystolicBP       31
AdmissionDate     0
HasInsurance     30
BillingAmount    32
dtype: int64
Duplicates: 15

In [9]:
df = df.drop_duplicates()
print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 408

In [10]:
text_cols = ['Name', 'Gender', 'Diagnosis', 'City', 'BloodType', 'HasInsurance']
for col in text_cols:
    df[col] = df[col].astype('string').str.strip()

In [11]:
df['Gender'] = df['Gender'].str.lower()

df['Gender'] = df['Gender'].replace({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female',
    '?': np.nan
})

In [12]:
df['Diagnosis'] = df['Diagnosis'].str.lower()

df['Diagnosis'] = df['Diagnosis'].replace({
    'asthma': 'Asthma',
    'athsma': 'Asthma',

    'arthritis': 'Arthritis',

    'bronchitis': 'Bronchitis',

    'anemia': 'Anemia',
    'anaemia': 'Anemia',

    'migraine': 'Migraine',
    'migrane': 'Migraine',

    'flu': 'Influenza',
    'influenza': 'Influenza',

    'diabetes': 'Type 2 Diabetes',
    'diabetis': 'Type 2 Diabetes',
    'type 2 diabetes': 'Type 2 Diabetes',

    'hypertension': 'Hypertension',
    'hyper tension': 'Hypertension',
    'high blood pressure': 'Hypertension'
})

In [13]:
df['City'] = df['City'].str.lower().str.strip()

df['City'] = df['City'].replace({
    'karachi': 'Karachi',
    'lahore': 'Lahore',
    'islamabad': 'Islamabad',
    'rawalpindi': 'Rawalpindi',
    'multan': 'Multan',
    'peshawar': 'Peshawar',
    'quetta': 'Quetta',
    'faisalabad': 'Faisalabad',
    'unknown': np.nan
})

In [14]:
df['HasInsurance'] = df['HasInsurance'].str.lower()

df['HasInsurance'] = df['HasInsurance'].replace({
    'yes': 1,
    'y': 1,
    '1': 1,
    'no': 0,
    'n': 0,
    '0': 0,
    '--': np.nan
})

In [15]:
df.loc[(df['Age'] < 0) | (df['Age'] > 100), 'Age'] = np.nan

df.loc[(df['HeightCM'] < 100) | (df['HeightCM'] > 250), 'HeightCM'] = np.nan

df.loc[(df['WeightKG'] < 20) | (df['WeightKG'] > 250), 'WeightKG'] = np.nan

df.loc[(df['SystolicBP'] < 60) | (df['SystolicBP'] > 250), 'SystolicBP'] = np.nan

In [16]:
df['BillingAmount'] = (
    df['BillingAmount']
    .astype('string')
    .str.replace('$', '', regex=False)
    .str.replace('PKR', '', regex=False)
    .str.strip()
)

df['BillingAmount'] = pd.to_numeric(df['BillingAmount'], errors='coerce')

In [17]:
df['AdmissionDate'] = pd.to_datetime(
    df['AdmissionDate'],
    errors='coerce',
    dayfirst=False
)

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
numeric_cols = [
    'Age',
    'HeightCM',
    'WeightKG',
    'SystolicBP',
    'BillingAmount'
]

categorical_cols = [
    'Gender',
    'Diagnosis',
    'City',
    'BloodType',
    'HasInsurance'
]

In [ ]:
numeric_pipeline = SimpleImputer(strategy='median')

categorical_pipeline = SimpleImputer(
    strategy='most_frequent'
)

In [ ]:
preprocessor = ColumnTransformer([
    ('numeric', numeric_pipeline, numeric_cols),
    ('categorical', categorical_pipeline, categorical_cols)
])

In [ ]:
X = df[numeric_cols + categorical_cols]

X_clean = preprocessor.fit_transform(X)

print(X_clean.shape)

In [ ]:
from sklearn.preprocessing import StandardScaler

X_numeric = df[numeric_cols]

X_numeric = SimpleImputer(strategy='median').fit_transform(X_numeric)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_numeric)

print(X_scaled[:5])

In [ ]:
df['AdmissionDate'] = df['AdmissionDate'].dt.strftime('%Y-%m-%d')

df.to_csv("hospital_patient_records_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")